services:
  - type: web
    name: agricart
    runtime: docker
    plan: free
    envVars:
      - key: DB_HOST
        value: sql207.infinityfree.com
      - key: DB_USER
        value: if0_42108185
      - key: DB_PASS
        value: jpSlFNwdGePrqE
      - key: DB_NAME
        value: if0_42108185_agricart
      - key: DB_PORT
        value: 3306
